bio: a band and a filmmaker from NYC are fighting homophobia through storytelling in the ongoing pursuit of human rights.
project_url: http://www.kickstarter.com/projects/289033959/dont-ask-me-why-a-music-video-by-great-caesar
tw_text: "Check out this #NYC band standing for #equality at http://kck.st/12dC8My #dontaskmewhy @greatcaesarband http://dontaskmewhy.org"
